# Sample code from Programming Ruby, page 436
# sort_by {| object | block } → array 
# sort_by → an_enumerator 
# Sorts enumerator using a set of keys generated by mapping the values in enum through the given
# block.

# If no block is given, an enumerator is returned instead.

# %w{ apple pear fig }.sort_by {|word| word.length}
#              => ["fig", "pear", "apple"]

set = %w{ apple pear fig }
set.send :display
puts
sorted = set.sort_by {|word| word.length}
sorted.send :display
puts